In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [3]:
#Load the dataset
data=pd.read_csv('Cutlets.csv')
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
unitA=pd.Series(data.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
unitB=pd.Series(data.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [6]:
p_value=stats.ttest_ind(unitA, unitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [39]:
p_value[1]

0.4722394724599501

as the p value is greater than 0.05
we will go with h0
which is unitA = unitB



In [41]:
#Q2 
LabTAT = pd.read_csv("labTAT.csv")
LabTAT

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

here, H0: L1 = L2 = L3 = L4
	Ha: one of them are not equal here we have to perform ANOVA test


In [56]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(LabTAT.iloc[:,0],LabTAT.iloc[:,1],LabTAT.iloc[:,2],LabTAT.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [57]:
p_value[1]

2.1156708949992414e-57

As we can see that the p_value is very less than 0.05
We can say that there is difference in average TAT among the different laboratories.

In [64]:
data = pd.read_csv("BuyerRatio.csv")
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [68]:
Table=data.iloc[:,1:6]
Table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

As the given data was in categorical form and then converted into tabular format
we will perform the chi square test
here, h0: all proportional are equal
      h1: all proportional are not equal

In [69]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

In [70]:
val = stats.chi2_contingency(Table)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [78]:
Expected_values = val[3]
Expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [80]:
#Observed_values 
Observed_values = Table.values
print("Observed_values:-\n",Observed_values)


Observed_values:-
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [85]:
no_of_rows = len(Table.iloc[0:2,0])
no_of_columns = len(Table.iloc[0,0:4])
ddof = (no_of_rows-1)*(no_of_columns-1)
print("Degree of freedom:-",ddof)
alpha = 0.05

Degree of freedom:- 3


In [86]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(Observed_values, Expected_values)])
chi_square_statistics=chi_square[0]+chi_square[1]


In [87]:
print("chi-square statistics:-",chi_square_statistics)

chi-square statistics:- 1.5152956451130446


In [88]:
critical_value = chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:', critical_value)

critical_value: 7.814727903251179


In [91]:
#Another method
p_value = 1-chi2.cdf(x=chi_square_statistics,df=ddof)
print('p-value:',p_value)
print('Significance level:',alpha)
print('Degree of freedom:',ddof)
print('p-value:',p_value)

p-value: 0.6787446296467897
Significance level: 0.05
Degree of freedom: 3
p-value: 0.6787446296467897


In [98]:
if p_value<=alpha:
	print("Reject H0, All proportions are equal.")
else:
	print("Accept H1,All proportions are not equal.")

Accept H1,All proportions are not equal.


In [105]:
import pandas as pd
from scipy import stats as stats
from scipy.stats import chi2_contingency
from scipy.stats import chi2


In [106]:
#Q4
telecall = pd.read_csv("Costomer+OrderForm.csv")
telecall

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [107]:
telecall.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [108]:
print(telecall['Phillippines'].value_counts(),telecall['Indonesia'].value_counts(),telecall['Malta'].value_counts(),telecall['India'].value_counts())



Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64


In [110]:
observed = ([271,267,269,280],[29,33,31,20])
observed

([271, 267, 269, 280], [29, 33, 31, 20])

In [111]:
stat, p, dof, expected = chi2_contingency([[271,267,269,280],[29,33,31,20]])
stat

3.858960685820355

In [112]:
p

0.2771020991233135

In [113]:
print('dof=%d' % dof)
print(expected)

dof=3
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [114]:
alpha = 0.05
q=1-alpha
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

significance=0.050, p=0.277
Independent (fail to reject H0)
